const ages = require("./ages");

module.exports = {
  gbs: {
    Observatory: { key: "Observatory", age: ages.NoAge.key },
    Temple_of_Relics: { key: "Temple_of_Relics", age: ages.NoAge.key },
    Oracle_of_Delphi: { key: "Oracle_of_Delphi", age: ages.NoAge.key },
    Tower_of_Babel: { key: "Tower_of_Babel", age: ages.BronzeAge.key },
    Statue_of_Zeus: { key: "Statue_of_Zeus", age: ages.BronzeAge.key },
    Colosseum: { key: "Colosseum", age: ages.IronAge.key },
    Lighthouse_of_Alexandria: { key: "Lighthouse_of_Alexandria", age: ages.IronAge.key },
    Hagia_Sophia: { key: "Hagia_Sophia", age: ages.EarlyMiddleAges.key },
    Cathedral_of_Aachen: { key: "Cathedral_of_Aachen", age: ages.EarlyMiddleAges.key },
    St_Mark_s_Basilica: { key: "St_Mark_s_Basilica", age: ages.HighMiddleAges.key },
    Notre_Dame: { key: "Notre_Dame", age: ages.HighMiddleAges.key },
    Saint_Basil_s_Cathedral: { key: "Saint_Basil_s_Cathedral", age: ages.LateMiddleAges.key },
    Castel_del_Monte: { key: "Castel_del_Monte", age: ages.LateMiddleAges.key },
    Deal_Castle: { key: "Deal_Castle", age: ages.ColonialAge.key },
    Frauenkirche_of_Dresden: { key: "Frauenkirche_of_Dresden", age: ages.ColonialAge.key },
    Capitol: { key: "Capitol", age: ages.IndustrialAge.key },
    Royal_Albert_Hall: { key: "Royal_Albert_Hall", age: ages.IndustrialAge.key },
    Chateau_Frontenac: { key: "Chateau_Frontenac", age: ages.ProgressiveEra.key },
    Alcatraz: { key: "Alcatraz", age: ages.ProgressiveEra.key },
    Space_Needle: { key: "Space_Needle", age: ages.ModernEra.key },
    Atomium: { key: "Atomium", age: ages.ModernEra.key },
    Cape_Canaveral: { key: "Cape_Canaveral", age: ages.PostmodernEra.key },
    The_Habitat: { key: "The_Habitat", age: ages.PostmodernEra.key },
    Lotus_Temple: { key: "Lotus_Temple", age: ages.ContemporaryEra.key },
    Innovation_Tower: { key: "Innovation_Tower", age: ages.ContemporaryEra.key },
    Dynamic_Tower: { key: "Dynamic_Tower", age: ages.Tomorrow.key },
    Voyager_V1: { key: "Voyager_V1", age: ages.Tomorrow.key },
    The_Arc: { key: "The_Arc", age: ages.TheFuture.key },
    Rain_Forest_Project: { key: "Rain_Forest_Project", age: ages.TheFuture.key },
    Gaea_Statue: { key: "Gaea_Statue", age: ages.ArcticFuture.key },
    Arctic_Orangery: { key: "Arctic_Orangery", age: ages.ArcticFuture.key },
    Seed_Vault: { key: "Seed_Vault", age: ages.ArcticFuture.key },
    Atlantis_Museum: { key: "Atlantis_Museum", age: ages.OceanicFuture.key },
    The_Kraken: { key: "The_Kraken", age: ages.OceanicFuture.key },
    The_Blue_Galaxy: { key: "The_Blue_Galaxy", age: ages.OceanicFuture.key }
  },

  gbList: [
    { key: "NoAge", gbs: ["Observatory", "Temple_of_Relics", "Oracle_of_Delphi"] },
    { key: "BronzeAge", gbs: ["Tower_of_Babel", "Statue_of_Zeus"] },
    { key: "IronAge", gbs: ["Colosseum", "Lighthouse_of_Alexandria"] },
    { key: "EarlyMiddleAges", gbs: ["Hagia_Sophia", "Cathedral_of_Aachen"] },
    { key: "HighMiddleAges", gbs: ["St_Mark_s_Basilica", "Notre_Dame"] },
    { key: "LateMiddleAges", gbs: ["Saint_Basil_s_Cathedral", "Castel_del_Monte"] },
    { key: "ColonialAge", gbs: ["Deal_Castle", "Frauenkirche_of_Dresden"] },
    { key: "IndustrialAge", gbs: ["Capitol", "Royal_Albert_Hall"] },
    { key: "ProgressiveEra", gbs: ["Chateau_Frontenac", "Alcatraz"] },
    { key: "ModernEra", gbs: ["Space_Needle", "Atomium"] },
    { key: "PostmodernEra", gbs: ["Cape_Canaveral", "The_Habitat"] },
    { key: "ContemporaryEra", gbs: ["Lotus_Temple", "Innovation_Tower"] },
    { key: "Tomorrow", gbs: ["Dynamic_Tower", "Voyager_V1"] },
    { key: "TheFuture", gbs: ["The_Arc", "Rain_Forest_Project"] },
    { key: "ArcticFuture", gbs: ["Gaea_Statue", "Arctic_Orangery", "Seed_Vault"] },
    { key: "OceanicFuture", gbs: ["Atlantis_Museum", "The_Kraken", "The_Blue_Galaxy"] }
  ],

  gbsData: {
    Observatory: require("./gbs-data/Observatory"),
    Temple_of_Relics: require("./gbs-data/Temple_of_Relics"),
    Oracle_of_Delphi: require("./gbs-data/Oracle_of_Delphi"),
    Tower_of_Babel: require("./gbs-data/Tower_of_Babel"),
    Statue_of_Zeus: require("./gbs-data/Statue_of_Zeus"),
    Colosseum: require("./gbs-data/Colosseum"),
    Lighthouse_of_Alexandria: require("./gbs-data/Lighthouse_of_Alexandria"),
    Hagia_Sophia: require("./gbs-data/Hagia_Sophia"),
    Cathedral_of_Aachen: require("./gbs-data/Cathedral_of_Aachen"),
    St_Mark_s_Basilica: require("./gbs-data/St_Mark_s_Basilica"),
    Notre_Dame: require("./gbs-data/Notre_Dame"),
    Saint_Basil_s_Cathedral: require("./gbs-data/Saint_Basil_s_Cathedral"),
    Castel_del_Monte: require("./gbs-data/Castel_del_Monte"),
    Deal_Castle: require("./gbs-data/Deal_Castle"),
    Frauenkirche_of_Dresden: require("./gbs-data/Frauenkirche_of_Dresden"),
    Capitol: require("./gbs-data/Capitol"),
    Royal_Albert_Hall: require("./gbs-data/Royal_Albert_Hall"),
    Chateau_Frontenac: require("./gbs-data/Chateau_Frontenac"),
    Alcatraz: require("./gbs-data/Alcatraz"),
    Space_Needle: require("./gbs-data/Space_Needle"),
    Atomium: require("./gbs-data/Atomium"),
    Cape_Canaveral: require("./gbs-data/Cape_Canaveral"),
    The_Habitat: require("./gbs-data/The_Habitat"),
    Lotus_Temple: require("./gbs-data/Lotus_Temple"),
    Innovation_Tower: require("./gbs-data/Innovation_Tower"),
    Dynamic_Tower: require("./gbs-data/Dynamic_Tower"),
    Voyager_V1: require("./gbs-data/Voyager_V1"),
    The_Arc: require("./gbs-data/The_Arc"),
    Rain_Forest_Project: require("./gbs-data/Rain_Forest_Project"),
    Gaea_Statue: require("./gbs-data/Gaea_Statue"),
    Arctic_Orangery: require("./gbs-data/Arctic_Orangery"),
    Seed_Vault: require("./gbs-data/Seed_Vault"),
    Atlantis_Museum: require("./gbs-data/Atlantis_Museum"),
    The_Kraken: require("./gbs-data/The_Kraken"),
    The_Blue_Galaxy: require("./gbs-data/The_Blue_Galaxy")
  },

  agesCost: {
    Oracle: require("./ages-cost/Oracle"),
    NoAge: require("./ages-cost/NoAge"),
    BronzeAge: require("./ages-cost/BronzeAge"),
    IronAge: require("./ages-cost/IronAge"),
    EarlyMiddleAges: require("./ages-cost/EarlyMiddleAges"),
    HighMiddleAges: require("./ages-cost/HighMiddleAges"),
    LateMiddleAges: require("./ages-cost/LateMiddleAges"),
    ColonialAge: require("./ages-cost/ColonialAge"),
    IndustrialAge: require("./ages-cost/IndustrialAge"),
    ProgressiveEra: require("./ages-cost/ProgressiveEra"),
    ModernEra: require("./ages-cost/ModernEra"),
    PostmodernEra: require("./ages-cost/PostmodernEra"),
    ContemporaryEra: require("./ages-cost/ContemporaryEra"),
    Tomorrow: require("./ages-cost/Tomorrow"),
    TheFuture: require("./ages-cost/TheFuture"),
    ArcticFuture: require("./ages-cost/ArcticFuture"),
    OceanicFuture: require("./ages-cost/OceanicFuture")
  }
};
